# Autogenerated wrapper script for GAP_pkg_io_jll for aarch64-linux-gnu
export io

using GAP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_io")
JLLWrappers.@declare_file_product(io)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll)
    JLLWrappers.@init_file_product(
        io,
        "lib/gap/io.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
